/// Application-wide constants
class AppConstants {
  AppConstants._();

  /// Application name
  static const String appName = 'DevPortMonitor';

  /// Application version
  static const String appVersion = '1.0.0';

  /// Port range to scan
  static const int minPort = 1024;
  static const int maxPort = 65535;

  /// Auto-refresh interval in seconds
  static const int refreshIntervalSeconds = 10;

  /// Development process patterns to detect
  static const List<String> devProcessPatterns = [
    // Node.js ecosystem
    'node',
    'nodemon',
    'npm',
    'npx',
    'yarn',
    'pnpm',
    'deno',
    'bun',
    // JavaScript frameworks/tools
    'webpack',
    'vite',
    'next',
    'nuxt',
    'remix',
    'astro',
    'gatsby',
    'parcel',
    'esbuild',
    'rollup',
    'turbo',
    'storybook',
    'cypress',
    'playwright',
    'jest',
    'vitest',
    'mocha',
    'express',
    'koa',
    'hapi',
    'fastify',
    'nest',
    'strapi',
    'directus',
    'prisma',
    'hasura',
    'supabase',
    'firebase',
    // Python
    'python',
    'python3',
    'uvicorn',
    'gunicorn',
    'flask',
    'django',
    'fastapi',
    'streamlit',
    'gradio',
    'jupyter',
    'celery',
    // Ruby
    'ruby',
    'rails',
    'puma',
    'unicorn',
    'sidekiq',
    'resque',
    // Java/JVM
    'java',
    'gradle',
    'maven',
    'spring',
    'tomcat',
    // PHP
    'php',
    'artisan',
    'composer',
    // Go
    'go',
    'gin',
    'fiber',
    // Rust
    'rust',
    'cargo',
    // .NET
    'dotnet',
    'kestrel',
    // Containers
    'docker',
    'podman',
    // Web servers
    'nginx',
    'apache',
    'httpd',
    'caddy',
    // Databases
    'redis',
    'mongo',
    'postgres',
    'mysql',
    'sqlite',
    // Desktop/Mobile
    'electron',
    'tauri',
    'flutter',
    'dart',
    'expo',
    'react-native',
    'ionic',
    'capacitor',
    // Process managers
    'pm2',
    'supervisor',
    // AI/ML
    'unity',
    'unity-mcp',
    'mcp',
    'openclaw',
    'ollama',
    'Ollama',
    'llama',
    'openai',
    'anthropic',
    'claude',
    'gpt',
    'langchain',
    'chromadb',
    'pinecone',
    'weaviate',
    'qdrant',
    'milvus',
    // IDEs and Code Editors
    'Code',
    'Code Helper',
    'code-server',
    'vscode',
    'cursor',
    'Cursor',
    'zed',
    'sublime',
    'atom',
    'webstorm',
    'intellij',
    'pycharm',
    'goland',
    'rider',
    // Communication/Collaboration
    'Discord',
    'slack',
    'Slack',
    // Google Services
    'Google',
    'Chrome',
  ];

  /// System processes to always exclude
  static const List<String> systemProcessExclusions = [
    'launchd',
    'kernel_task',
    'WindowServer',
    'loginwindow',
    'System',
    'systemd',
    'init',
    'svchost',
    'csrss',
    'wininit',
    'services',
    'lsass',
    'smss',
    'dwm',
    'explorer',
    'Finder',
    'Dock',
    'Spotlight',
    'mds',
    'mds_stores',
    'mdworker',
    'coreaudiod',
    'bluetoothd',
    'airportd',
    'WiFiAgent',
    'UserEventAgent',
    'cfprefsd',
    'distnoted',
    'trustd',
    'securityd',
    'syspolicyd',
    'rapportd',
    'cloudd',
    'sharingd',
    'bird',
    'secd',
    'nsurlsessiond',
    'com.apple',
    'AppleSpell',
    'assistantd',
    'callservicesd',
    'mediaremoted',
    'coreduetd',
    'duetexpertd',
    'suggestd',
    'parsecd',
    'knowledge',
    'pboard',
    'fontd',
    'tccd',
    'containermanager',
    'siriknowledged',
    'routined',
    'ContextStoreAgent',
    'CoreLocationAgent',
    'LocationMenu',
    'WirelessRadioManagerd',
    'symptomsd',
    'lsd',
    'logd',
    'notifyd',
    'configd',
    'powerd',
    'corebrightnessd',
    'iconservicesagent',
    'corespotlightd',
    'fseventsd',
    'deleted',
    'diskarbitrationd',
    'storeassetd',
    'softwareupdated',
    'pkd',
    'accountsd',
    'akd',
    'amsaccountsd',
    'appstoreagent',
    'biomed',
    'biomesyncd',
  ];

  /// Category names for grouping
  static const Map<String, List<String>> processCategories = {
    'JavaScript/Node': [
      'node',
      'nodemon',
      'npm',
      'npx',
      'yarn',
      'pnpm',
      'deno',
      'bun',
    ],
    'Python': [
      'python',
      'python3',
      'uvicorn',
      'gunicorn',
      'flask',
      'django',
      'jupyter',
      'streamlit',
      'gradio',
      'fastapi',
      'celery',
    ],
    'Ruby': ['ruby', 'rails', 'puma', 'unicorn', 'sidekiq', 'resque'],
    'Java/JVM': ['java', 'gradle', 'maven', 'spring', 'tomcat'],
    'PHP': ['php', 'artisan', 'composer'],
    'Go': ['go', 'gin', 'fiber'],
    'Rust': ['rust', 'cargo'],
    '.NET': ['dotnet', 'kestrel'],
    'Build Tools': [
      'webpack',
      'vite',
      'parcel',
      'esbuild',
      'rollup',
      'turbo',
    ],
    'Frameworks': [
      'next',
      'nuxt',
      'remix',
      'astro',
      'gatsby',
      'express',
      'koa',
      'hapi',
      'fastify',
      'nest',
      'strapi',
      'directus',
    ],
    'Database': [
      'redis',
      'mongo',
      'postgres',
      'mysql',
      'sqlite',
      'prisma',
      'hasura',
    ],
    'DevOps': [
      'docker',
      'podman',
      'nginx',
      'apache',
      'httpd',
      'caddy',
      'pm2',
      'supervisor',
    ],
    'Desktop/Mobile': [
      'electron',
      'tauri',
      'flutter',
      'dart',
      'expo',
      'react-native',
      'ionic',
      'capacitor',
    ],
    'Testing': [
      'storybook',
      'cypress',
      'playwright',
      'jest',
      'vitest',
      'mocha',
    ],
    'Cloud/BaaS': ['supabase', 'firebase'],
    'AI/ML': [
      'ollama',
      'llama',
      'openai',
      'anthropic',
      'claude',
      'gpt',
      'langchain',
      'chromadb',
      'pinecone',
      'weaviate',
      'qdrant',
      'milvus',
      'mlflow',
      'tensorboard',
    ],
    'MCP/Tools': [
      'mcp',
      'unity-mcp',
      'openclaw',
      'unity',
    ],
    'IDE/Editors': [
      'Code',
      'Code Helper',
      'code-server',
      'vscode',
      'cursor',
      'Cursor',
      'zed',
      'sublime',
      'atom',
      'webstorm',
      'intellij',
      'pycharm',
      'goland',
      'rider',
    ],
    'Communication': [
      'Discord',
      'slack',
      'Slack',
    ],
  };
}
